# Generated by Django 2.1.3 on 2018-11-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times_api', '0002_auto_20181115_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
