# Generated by Django 2.1.3 on 2018-11-15 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('times_api', '0004_auto_20181115_2244'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
    ]
